name: Build and Release Daily App

on:
  push:
    tags:
      - 'v*'  # Triggert bei Tags wie v1.0.0, v1.1.0, etc.
  workflow_dispatch:  # Erlaubt manuellen Trigger

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build Swift Package
      run: |
        swift build -c release
        
    - name: Create App Bundle
      run: |
        # Erstelle App Bundle Struktur
        mkdir -p "Daily App.app/Contents/MacOS"
        mkdir -p "Daily App.app/Contents/Resources"
        
        # Kopiere die Binary
        cp .build/release/DailyApp "Daily App.app/Contents/MacOS/Daily App"
        
        # Erstelle Info.plist
        cat > "Daily App.app/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>Daily App</string>
            <key>CFBundleIdentifier</key>
            <string>com.andre.dailyapp</string>
            <key>CFBundleName</key>
            <string>Daily App</string>
            <key>CFBundleDisplayName</key>
            <string>Daily App</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>LSUIElement</key>
            <true/>
            <key>LSMinimumSystemVersion</key>
            <string>15.0</string>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>NSRequiresAquaSystemAppearance</key>
            <false/>
        </dict>
        </plist>
        EOF
        
    - name: Code Sign App (Optional)
      if: false  # Deaktiviert da du wahrscheinlich kein Developer Certificate hast
      run: |
        codesign --force --deep --sign - "Daily App.app"
        
    - name: Create DMG
      run: |
        # Erstelle einen temporären Ordner für das DMG
        mkdir dmg-temp
        cp -R "Daily App.app" dmg-temp/
        
        # Erstelle das DMG
        hdiutil create -volname "Daily App" -srcfolder dmg-temp -ov -format UDZO "Daily-App.dmg"
        
    - name: Create ZIP Archive
      run: |
        zip -r "Daily-App.zip" "Daily App.app"
        
    - name: Get Release Info
      id: release_info
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "is_tag=true" >> $GITHUB_OUTPUT
        else
          echo "tag_name=dev-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_OUTPUT
          echo "is_tag=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Daily App ${{ steps.release_info.outputs.tag_name }}
        body: |
          ## Daily App - macOS Liquid Glass Edition
          
          Eine native macOS Menu Bar App zum Tracken deiner täglichen Aufgaben.
          
          ### Features:
          - 🎨 Liquid Glass Design für macOS Tahoe (15.0+)
          - ⌨️ Globales Tastenkürzel: `Cmd+Shift+D`
          - 📝 Schnelle Texteingabe für tägliche Tasks
          - 💾 Automatische Speicherung
          - 🌙 Spotlight-artiges Interface
          
          ### Installation:
          1. `Daily-App.dmg` herunterladen
          2. DMG öffnen und App in den Applications Ordner ziehen
          3. App starten - Icon erscheint in der Menüleiste
          4. `Cmd+Shift+D` drücken zum Öffnen
          
          ### Systemvoraussetzungen:
          - macOS Tahoe (15.0) oder neuer
          - Apple Silicon oder Intel Mac
          
        files: |
          Daily-App.dmg
          Daily-App.zip
        draft: false
        prerelease: false
